FROM node:alpine
WORKDIR /usr/app

COPY ./package.json ./
RUN npm install

# Copy isn't technically needed when using docker-compose.dev when using volumes
# to map to the local source files.
# COPY . .

CMD ["npm", "run", "start"]